name: deepfakesonly
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - libexpat=2.6.2
  - libffi=3.4.2
  - libsqlite=3.45.3
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.0
  - pip=24.0
  - python=3.11.9
  - readline=8.2
  - setuptools=70.0.0
  - tk=8.6.13
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
      - bleach==6.1.0
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - filelock==3.14.0
      - fsspec==2024.5.0
      - idna==3.7
      - jinja2==3.1.4
      - kaggle==1.6.14
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - opencv-python==4.10.0.82
      - opendatasets==0.1.22
      - pandas==2.0.3
      - pillow==10.3.0
      - python-dateutil==2.9.0.post0
      - python-slugify==8.0.4
      - pytz==2024.1
      - requests==2.32.3
      - six==1.16.0
      - sympy==1.12.1
      - text-unidecode==1.3
      - torch==2.2.2
      - torchvision==0.17.2
      - tqdm==4.66.4
      - typing-extensions==4.12.1
      - tzdata==2024.1
      - urllib3==2.2.1
      - webencodings==0.5.1
